import {
  TextEffectOne,
  TextEffectThree,
  TextEffectTwo,
  TextEffectFour,
} from 'react-text-animate'

const components = [
  {
    name: TextEffectOne,
    snippet: '<TextEffectOne />',
    href: '/1',
    text: 'HOW YOU DOIN ?',
    hidePlay: false,
  },
  {
    name: TextEffectTwo,
    snippet: '<TextEffectTwo />',
    href: '/2',
    text: 'The quick brown fox jumps over the lazy dog.',
    hidePlay: false,
  },
  {
    name: TextEffectThree,
    snippet: '<TextEffectThree />',
    href: '/3',
    text: 'HOVER ME!',
    hidePlay: true,
  },
  {
    name: TextEffectFour,
    snippet: '<TextEffectFour />',
    href: '/4',
    text: 'Watch as each character appears one by one!',
  },
]

const words = [
  'Elegant',
  'Radiant',
  'Serene',
  'Exquisite',
  'Charming',
  'Vibrant',
  'Majestic',
  'Graceful',
  'Enchanting',
  'Luminous',
  'Picturesque',
  'Delicate',
  'Stunning',
  'Alluring',
  'Mesmerizing',
  'Dazzling',
  'Ethereal',
  'Splendid',
  'Breathtaking',
  'Impressive',
  'Tranquil',
  'Divine',
  'Vivid',
  'Pristine',
  'Sumptutous',
  'Magnificient',
  'Captivating',
  'Glamorous',
  'Sublime',
  'Resplendent',
  'Refined',
  'Flawless',
  'Heavenly',
  'Authentic',
  'Marvelous',
  'Delightful',
  'Superb',
  'Ravishing',
  'Bewitching',
  'Authentic',
  'Evocative',
  'Mystic',
  'Luxurious',
]

const sentences = [
  'The garden was filled with radiant flowers🌼 that brightened up the entire landscape.',
  'The luminous glow of the moon🌔 added a touch of magic to the evening.',
  'The sunset over the mountains🌄 was truly breathtaking, with its vibrant hues.',
  'The serene lake mirrored the majestic peaks🏔️ in the background.',
  'Her dress was elegant and perfectly suited for the grand👑 occasion.',
  'Walking through the ancient forest🌳 was an enchanting experience.',
  'The artist’s latest work is nothing short of exquisite and captivating.',
  'The delicate details on the sculpture were incredibly charming.',
  'Their home was decorated in a glamorous style that was both sublime and opulent.',
  'The ethereal beauty of the early morning mist made the scene look like a dream.',
]

export { components, words, sentences }
